### ISSUE TITLE
Rename the exported "middleware" function

### ISSUE THREAD

**Issue by eilgin** [uphold/koa-pagination#47]
Is it possible to rename this generic `middleware` function into something more meaningful like `paginate`? This `middleware` function could overlap with other objects.

What do you think?

**Comment by franciscocardoso** [comment]
Hi @eilgin,

Sorry for the delay on this. You can rename the middleware:

```js
const { middleware: paginate } = require('koa-pagination');
```

**Comment by eilgin** [comment]
That's what i've done. Thanks anyway ;)
