### ISSUE TITLE
Prevent changing the status code

### ISSUE THREAD

**Issue by eilgin** [uphold/koa-pagination#48]
This project changes the response [HTTP status code](https://github.com/uphold/koa-pagination#codes) by **force**. it'd better if we could disallow this middleware from changing the status code based on heuristics.

What do you think?

_PS: Is the project unmaintained?_

**Comment by franciscocardoso** [comment]
Hi @eilgin,

This module changes the response according to `rfc2616`.

What is you use case?

**Comment by eilgin** [comment]
I'm trying to retrieve the first 100 users but since i'm not connected i want to return the "unauthorized" code (using `ctx.status = 401`) but this status is "swallowed" by this middleware [here](https://github.com/uphold/koa-pagination/blob/099c724b78a4e82401acea51ced4514039358f40/src/index.js#L105-L107) only because the request contains a "Range" header...

**Comment by franciscocardoso** [comment]
Hi @eilgin 

Did you try to set your authorisation middleware before.
You should authorise the request before trying to handle it.

Something like:

```js
app.get('/', security(), pagination(), async ctx => {});
```

This way, if the request is not authorised `pagination` will never be executed.

**Comment by eilgin** [comment]
@franciscocardoso yes i'm doing that but unfortunately the error response (401) is given by the user API (which is called by the current Koa app) so i can't predict in advance if the request will be rejected or not.

**Comment by franciscocardoso** [comment]
Hi @eilgin,

Not sure what you mean by `the error response (401) is given by the user API (which is called by the current Koa app)` but, either way, looks like that's just some missing error handling on your app.

```js
app.get('/', security(), pagination(), async ctx => {
  // call to the user API
  // "throw an error" if you get a 401 from the user API
});
```

Throwing that error will kill the process [here](https://github.com/uphold/koa-pagination/blob/master/src/index.js#L76), therefore, status code will not be changed by the pagination middleware.

**Comment by eilgin** [comment]
OK i understand what you're saying but i've found that i needed to change to time when the API is checking the ACL so it shouldn't be related to this issue anymore.

I'm going to close this issue. Thanks for your quick responses ;)
